"""Add provider team

Revision ID: 806d78e24b6f
Revises: f0ddfb38a2b6
Create Date: 2026-02-08 14:24:54.754948

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "806d78e24b6f"
down_revision: Union[str, Sequence[str], None] = "f0ddfb38a2b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("API_SPORTS", "NFLVERSE", "ODDS_API", name="provider_enum"),
            nullable=False,
        ),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("provider_team_id", sa.String(length=64), nullable=False),
        sa.Column("provider_team_name", sa.String(length=120), nullable=True),
        sa.Column("country_code", sa.String(length=8), nullable=True),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "provider_team_id", name="uq_provider_teams_provider_provider_team_id"
        ),
        sa.UniqueConstraint("provider", "team_id", name="uq_provider_teams_provider_team_id"),
    )
    op.create_index(
        op.f("ix_provider_teams_provider"), "provider_teams", ["provider"], unique=False
    )
    op.create_index(op.f("ix_provider_teams_team_id"), "provider_teams", ["team_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_provider_teams_team_id"), table_name="provider_teams")
    op.drop_index(op.f("ix_provider_teams_provider"), table_name="provider_teams")
    op.drop_table("provider_teams")
    # ### end Alembic commands ###
