"""Initial models

Revision ID: f0ddfb38a2b6
Revises: 
Create Date: 2026-02-06 10:02:42.879568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0ddfb38a2b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_books_is_active', 'books', ['is_active'], unique=False)
    op.create_index('ix_books_key', 'books', ['key'], unique=True)
    op.create_table('ingested_payloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_key', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('payload_json', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingested_payloads_lookup', 'ingested_payloads', ['provider', 'entity_type', 'entity_key', 'fetched_at'], unique=False)
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sport', sa.Enum('BASEBALL', 'BASKETBALL', 'FOOTBALL', 'HOCKEY', 'SOCCER', name='sportenum'), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_key')
    )
    op.create_index('ix_leagues_sport_active', 'leagues', ['sport', 'is_active'], unique=False)
    op.create_table('provider_sports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('API_SPORTS', 'NFLVERSE', 'ODDS_API', name='provider_enum'), nullable=False),
    sa.Column('sport', sa.Enum('BASEBALL', 'BASKETBALL', 'FOOTBALL', 'HOCKEY', 'SOCCER', name='sport_enum'), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'sport', name='uq_provider_sports_provider_sport')
    )
    op.create_index(op.f('ix_provider_sports_provider'), 'provider_sports', ['provider'], unique=False)
    op.create_index(op.f('ix_provider_sports_sport'), 'provider_sports', ['sport'], unique=False)
    op.create_table('provider_leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('API_SPORTS', 'NFLVERSE', 'ODDS_API', name='provider_enum'), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('provider_league_id', sa.String(length=64), nullable=False),
    sa.Column('provider_league_name', sa.String(length=120), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'league_id', name='uq_provider_leagues_provider_league_id'),
    sa.UniqueConstraint('provider', 'provider_league_id', name='uq_provider_leagues_provider_provider_league_id')
    )
    op.create_index(op.f('ix_provider_leagues_league_id'), 'provider_leagues', ['league_id'], unique=False)
    op.create_index(op.f('ix_provider_leagues_provider'), 'provider_leagues', ['provider'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'year', name='uq_seasons_league_year')
    )
    op.create_index('ix_seasons_league_active', 'seasons', ['league_id', 'is_active'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('provider_team_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbreviation', sa.String(), nullable=True),
    sa.Column('market', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'provider_team_id', name='uq_teams_league_provider_team_id')
    )
    op.create_index('ix_teams_abbreviation', 'teams', ['abbreviation'], unique=False)
    op.create_index('ix_teams_league_active', 'teams', ['league_id', 'is_active'], unique=False)
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('provider_venue_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('is_indoor', sa.Boolean(), nullable=True),
    sa.Column('roof_type', sa.Enum('DOME', 'RETRACTABLE', 'OPEN', 'UNKNOWN', name='rooftypeenum'), nullable=True),
    sa.Column('surface_type', sa.Enum('GRASS', 'TURF', 'HYBRID', 'UNKNOWN', name='surfacetypeenum'), nullable=True),
    sa.Column('altitude_m', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'name', 'city', name='uq_venues_league_name_city'),
    sa.UniqueConstraint('provider_venue_id')
    )
    op.create_index('ix_venues_lat_lon', 'venues', ['latitude', 'longitude'], unique=False)
    op.create_index('ix_venues_league_name', 'venues', ['league_id', 'name'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('provider_game_id', sa.String(), nullable=False),
    sa.Column('provider', sa.Enum('api_sports', 'nflverse', 'odds_api', name='providerenum'), server_default=sa.text("'api_sports'"), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'FINAL', 'POSTPONED', 'CANCELED', 'UNKNOWN', name='gamestatusenum'), nullable=False),
    sa.Column('is_neutral_site', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('source_last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_game_id', name='uq_game_provider_ext_id')
    )
    op.create_index('ix_games_away_team', 'games', ['away_team_id'], unique=False)
    op.create_index('ix_games_home_team', 'games', ['home_team_id'], unique=False)
    op.create_index('ix_games_league_start_time', 'games', ['league_id', 'start_time'], unique=False)
    op.create_index('ix_games_season_start_time', 'games', ['season_id', 'start_time'], unique=False)
    op.create_index('ix_games_venue_start_time', 'games', ['venue_id', 'start_time'], unique=False)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('market_type', sa.Enum('SPREAD', 'TOTAL', 'MONEYLINE', name='markettypeenum'), nullable=False),
    sa.Column('side_type', sa.Enum('HOME', 'AWAY', 'OVER', 'UNDER', name='sidetypeenum'), nullable=False),
    sa.Column('line', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('is_closing', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('provider', sa.String(), server_default='odds-api', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'book_id', 'market_type', 'side_type', 'captured_at', name='uq_odds_snapshots_identity')
    )
    op.create_index('ix_odds_snapshots_book_captured_at', 'odds_snapshots', ['book_id', 'captured_at'], unique=False)
    op.create_index('ix_odds_snapshots_closing_by_game_market_side', 'odds_snapshots', ['game_id', 'market_type', 'side_type'], unique=False, postgresql_where=sa.text('is_closing = true'))
    op.create_index('ix_odds_snapshots_game_captured_at', 'odds_snapshots', ['game_id', 'captured_at'], unique=False)
    op.create_index('ix_odds_snapshots_game_market_side_captured_at', 'odds_snapshots', ['game_id', 'market_type', 'side_type', 'captured_at'], unique=False)
    op.create_index('ix_odds_snapshots_lookup', 'odds_snapshots', ['game_id', 'book_id', 'market_type', 'side_type', 'captured_at'], unique=False)
    op.create_table('team_game_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('avg_points_for', sa.Float(), nullable=False),
    sa.Column('avg_points_against', sa.Float(), nullable=False),
    sa.Column('avg_point_diff', sa.Float(), nullable=False),
    sa.Column('off_pts_l3', sa.Float(), nullable=False),
    sa.Column('off_pts_l5', sa.Float(), nullable=False),
    sa.Column('off_pts_season', sa.Float(), nullable=False),
    sa.Column('off_diff_l3', sa.Float(), nullable=False),
    sa.Column('off_diff_l5', sa.Float(), nullable=False),
    sa.Column('off_diff_season', sa.Float(), nullable=False),
    sa.Column('off_yards_l3', sa.Float(), nullable=False),
    sa.Column('off_yards_l5', sa.Float(), nullable=False),
    sa.Column('off_yards_season', sa.Float(), nullable=False),
    sa.Column('off_turnovers_l3', sa.Float(), nullable=False),
    sa.Column('off_turnovers_l5', sa.Float(), nullable=False),
    sa.Column('off_turnovers_season', sa.Float(), nullable=False),
    sa.Column('def_pa_l3', sa.Float(), nullable=False),
    sa.Column('def_pa_l5', sa.Float(), nullable=False),
    sa.Column('def_pa_season', sa.Float(), nullable=False),
    sa.Column('def_diff_l3', sa.Float(), nullable=False),
    sa.Column('def_diff_l5', sa.Float(), nullable=False),
    sa.Column('def_diff_season', sa.Float(), nullable=False),
    sa.Column('def_yards_allowed_l3', sa.Float(), nullable=False),
    sa.Column('def_yards_allowed_l5', sa.Float(), nullable=False),
    sa.Column('def_yards_allowed_season', sa.Float(), nullable=False),
    sa.Column('def_takeaways_l3', sa.Float(), nullable=False),
    sa.Column('def_takeaways_l5', sa.Float(), nullable=False),
    sa.Column('def_takeaways_season', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'game_id', name='uq_team_game_state_team_game')
    )
    op.create_index('ix_team_game_state_game', 'team_game_state', ['game_id'], unique=False)
    op.create_index('ix_team_game_state_season_week', 'team_game_state', ['season_id', 'week'], unique=False)
    op.create_index('ix_team_game_state_team_start_time', 'team_game_state', ['team_id', 'start_time'], unique=False)
    op.create_table('team_game_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'team_id', name='uq_team_game_stats_game_team')
    )
    op.create_index('ix_tgs_game_id', 'team_game_stats', ['game_id'], unique=False)
    op.create_index('ix_tgs_team_id', 'team_game_stats', ['team_id'], unique=False)
    op.create_table('baseball_team_game_stats',
    sa.Column('team_game_stats_id', sa.Integer(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.Column('home_runs', sa.Integer(), nullable=True),
    sa.Column('walks', sa.Integer(), nullable=True),
    sa.Column('strikeouts', sa.Integer(), nullable=True),
    sa.Column('stats_json', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['team_game_stats_id'], ['team_game_stats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_game_stats_id')
    )
    op.create_table('football_team_game_stats',
    sa.Column('team_game_stats_id', sa.Integer(), nullable=False),
    sa.Column('yards_total', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('stats_json', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['team_game_stats_id'], ['team_game_stats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_game_stats_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('football_team_game_stats')
    op.drop_table('baseball_team_game_stats')
    op.drop_index('ix_tgs_team_id', table_name='team_game_stats')
    op.drop_index('ix_tgs_game_id', table_name='team_game_stats')
    op.drop_table('team_game_stats')
    op.drop_index('ix_team_game_state_team_start_time', table_name='team_game_state')
    op.drop_index('ix_team_game_state_season_week', table_name='team_game_state')
    op.drop_index('ix_team_game_state_game', table_name='team_game_state')
    op.drop_table('team_game_state')
    op.drop_index('ix_odds_snapshots_lookup', table_name='odds_snapshots')
    op.drop_index('ix_odds_snapshots_game_market_side_captured_at', table_name='odds_snapshots')
    op.drop_index('ix_odds_snapshots_game_captured_at', table_name='odds_snapshots')
    op.drop_index('ix_odds_snapshots_closing_by_game_market_side', table_name='odds_snapshots', postgresql_where=sa.text('is_closing = true'))
    op.drop_index('ix_odds_snapshots_book_captured_at', table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_index('ix_games_venue_start_time', table_name='games')
    op.drop_index('ix_games_season_start_time', table_name='games')
    op.drop_index('ix_games_league_start_time', table_name='games')
    op.drop_index('ix_games_home_team', table_name='games')
    op.drop_index('ix_games_away_team', table_name='games')
    op.drop_table('games')
    op.drop_index('ix_venues_league_name', table_name='venues')
    op.drop_index('ix_venues_lat_lon', table_name='venues')
    op.drop_table('venues')
    op.drop_index('ix_teams_league_active', table_name='teams')
    op.drop_index('ix_teams_abbreviation', table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_seasons_league_active', table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_provider_leagues_provider'), table_name='provider_leagues')
    op.drop_index(op.f('ix_provider_leagues_league_id'), table_name='provider_leagues')
    op.drop_table('provider_leagues')
    op.drop_index(op.f('ix_provider_sports_sport'), table_name='provider_sports')
    op.drop_index(op.f('ix_provider_sports_provider'), table_name='provider_sports')
    op.drop_table('provider_sports')
    op.drop_index('ix_leagues_sport_active', table_name='leagues')
    op.drop_table('leagues')
    op.drop_index('ix_ingested_payloads_lookup', table_name='ingested_payloads')
    op.drop_table('ingested_payloads')
    op.drop_index('ix_books_key', table_name='books')
    op.drop_index('ix_books_is_active', table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###
